'use client'
import NavBar from '@/components/NavBar'
import './globals.css'
import { Inter } from 'next/font/google'
import Footer from '@/components/Footer'
import { AnimatePresence } from 'framer-motion'
import { motion } from 'framer-motion'
import { usePathname } from 'next/navigation'

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const pathname = usePathname()
  return (
    <html lang='en'>
      <body suppressHydrationWarning={true} className={inter.className}>
        <NavBar />
        <AnimatePresence mode='wait'>
          <motion.div key={pathname}>{children}</motion.div>
        </AnimatePresence>
        <Footer />
      </body>
    </html>
  )
}
